BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from home.views import home
from aboutme.views import aboutme
from contactme.views import contactme



urlpatterns = [
    path('admin/', admin.site.urls, name="yönetim"),

    path("account/", include("accounts.urls"), name="hesaplar"),

    path("", home, name="anasayfa"),

    path("aboutme/", aboutme, name="hakkimda"),

    path("contactme/", contactme, name="iletisim"),

    path("posts/", include("post.urls"), name="gonderiler"),
]



urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import *



app_name = "accounts"



urlpatterns = [
    path("login", login_view, name="login"),

    path("logout", logout_view, name="logout"),

    path("register", register_view, name="register"),
]

post/urls.py
from django.urls import path
from .views import *



app_name = "post"



urlpatterns = [
    path("", posts, name="posts"),
    path("create", posts_create, name="create"),
    path("<slug>", posts_detail, name="detail"),
    path("<slug>/update", posts_update, name="update"),
    path("<slug>/delete", posts_delete, name="delete"),
]

aboutme/models.py
from django.db import models

contactme/models.py
from django.db import models

home/models.py
from django.db import models

aboutme/views.py
from django.shortcuts import render



def aboutme(request):

    return render(request, "aboutme.html")

contactme/views.py
from django.shortcuts import render



def contactme(request):

    return render(request, "contactme.html")

home/views.py
from django.shortcuts import render



def home(request):

    return render(request, "home.html")

templates/aboutme.html
{% extends "base.html" %}

{% block title %} About Me - {{ block.super }} {% endblock %}

{% block body %}



    Burası hakkımda



{% endblock %}

templates/base.html
<!DOCTYPE html>

{% load static %}



<html lang="en">

<head>



    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %} Emre Erden {% endblock %}</title>

    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">

    <link rel="stylesheet" href="{% static "css/style.css" %}">



</head>

<body>



    {% include "header.html" %}

    <script src="{% static "js/jquery.js" %}"></script>

    <script src="{% static "js/bootstrap.js" %}"></script>

    {% block body %}

    {% endblock %}



</body>

</html>

templates/contactme.html
{% extends "base.html" %}

{% block title %} Contact Me - {{ block.super }} {% endblock %}

{% block body %}



    Burası iletişim



{% endblock %}

templates/header.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">

    <a class="navbar-brand" href="{% url "anasayfa" %}">Homepage</a>



<!--------------------------------------------------- Responsive --------------------------------------------------->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
<!------------------------------------------ Responsive -------------------------------------->



        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav mr-auto">

                <li class="nav-item active">
                    <a class="nav-link" href="{% url "post:posts" %}">Posts<span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url "hakkimda" %}">About Me</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url "iletisim" %}">Contact Me</a>
                </li>



<!--------------------------------------------------- Dropdown Menu --------------------------------------------------->
                <li class="nav-item dropdown">

                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin Paneli</a>

                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                        {% if request.user.is_authenticated %}
                        {% else %}
                            <a class="dropdown-item" href="{% url "accounts:login" %}">Giriş Yap</a>
                            <a class="dropdown-item" href="{% url "accounts:register" %}">Üye Ol</a>
                        {% endif %}

                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item" href="{% url "post:create" %}">Yazı Ekle</a>
                            <a class="dropdown-item" href="{% url "accounts:logout" %}">Çıkış Yap</a>
                        {% endif %}

                        {% if request.user.is_authenticated %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/admin">Yönetim Paneli</a>
                        {% endif %}

                    </div>

                </li>
<!--------------------------------------------------- Dropdown Menu --------------------------------------------------->



            </ul>



<!--------------------------------------------------- Search --------------------------------------------------->
            <form class="form-inline my-2 my-lg-0" role="search" method="GET" action="">
                    <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <!--------------------------------------------------- Search --------------------------------------------------->



        </div>

</nav>

templates/home.html
{% extends "base.html" %}

{% block title %} Homepage - {{ block.super }} {% endblock %}

{% block body %}



    Burası Anasayfa

    <br><br><br>

    Hoşgeldiniz, Kullanıcı: {{ request.user }}



{% endblock %}